version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    depends_on:
      - db
    build: .
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/workdir"

volumes:
  db: