version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    depends_on:
      - db
    build: .
    ports:
      - "3001:3001"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: aws-taskmaster.c1j7ubdkf9mu.ap-southeast-1.rds.amazonaws.com
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/workdir"

volumes:
  db:
  mysql: